---
- name: Configuration - Ensure testlink directory is present.
  file:
    path: "{{ testlink_install_dir }}"
    state: directory

- name: Configuration - Ensure links are created.
  file:
    src: "{{ testlink_install_dir }}"
    dest: "{{ item }}"
    owner: "{{ testlink_user }}"
    group: "{{ testlink_group }}"
    state: link
    mode: 'g+rwx'
  with_items:
  - '/var/www/testlink'
  - "{{ testlink_var_dir }}"

- name: Configuration - Ensure directories writeable by group.
  file:
    path: "{{ item }}"
    mode: '0775'
    state: directory
  with_items:
  - "{{ testlink_var_dir }}/logs/"
  - "{{ testlink_var_dir }}/upload_area/"
  - "{{ testlink_var_dir }}/upload_area/executions"
  - "{{ testlink_var_dir }}/upload_area/execution_tcsteps"
  - "{{ testlink_var_dir }}/upload_area/nodes_hierarchy"
  - "{{ testlink_var_dir }}/gui/templates_c"

- name: Configuration - Ensure log link is created.
  file:
    src: "{{ testlink_install_dir }}/logs"
    dest: "/var/log/testlink"
    owner: "{{ testlink_user }}"
    group: "{{ testlink_group }}"
    state: link

- name: Configuration - Ensure config files are present.
  template:
    src: "{{ item }}.j2"
    dest: "{{ testlink_install_dir }}/{{ item }}"
    mode: 0664
  with_items:
  - 'config_db.inc.php'
  - 'custom_config.inc.php'

- name: Configuration - Ensure testlink ownership.
  file:
    path: "{{ testlink_install_dir }}"
    owner: "{{ testlink_user }}"
    group: "{{ testlink_group }}"
    recurse: yes
  when: (testlink_git_result is defined and testlink_git_result.changed) or
        (testlink_unarchived is defined and testlink_unarchived.changed)
