---
- name: Installation - Download testlink.
  get_url:
    url: "{{ teslink_package_url }}"
    dest: "/tmp/testlink.tar.gz"

- name: Installation - Unarchive testlink.
  unarchive:
    src: "/tmp/testlink.tar.gz"
    dest: "/var/www"
    copy: no

- name: Installation - Create link.
  file:
    src: "/var/www/testlink-{{ testlink_version }}"
    dest: "/var/www/testlink"
    state: link

