---
- name: Ensure testlink group is present.
  group:
    name: "{{ testlink_group }}"
    state: present

- name: Ensure testlink user is present.
  user:
    name: "{{ testlink_user }}"
    group: "{{ testlink_group }}"
    state: present

- name: Retrieve testlink group members.
  getent:
    database: group
    key: "{{ testlink_group }}"

- name: Ensure webserver user is in the testlink group.
  user:
    name: "{{ testlink_webserver_user }}"
    groups: "{{ testlink_group }}"
  when: not testlink_webserver_user in getent_group['{{ testlink_group }}'][2]

- include_tasks: installation.yml
  when: testlink_version | lower != 'latest'

- include_tasks: latest.yml
  when: testlink_version | lower == 'latest'

- include_tasks: configuration.yml

- include_tasks: "{{ testlink_dbms }}.yml"
  when: testlink_dbms != False

- name: stat install directory.
  stat:
    path: '/var/www/testlink/install'
  register: testlink_install

- name: Ensure install directory is absent.
  command: "mv /var/www/testlink/install /var/www/testlink/install.origin"
  args:
    creates: "/var/www/testlink/install.origin"
  when: testlink_install.stat.exists
