---
- name: Ensure PHP prerequisites are present.
  include_tasks: php.yml

- name: Ensure testlink group is present.
  group:
    name: "{{ testlink_group }}"
    state: present

- name: Ensure testlink user is present.
  user:
    name: "{{ testlink_user }}"
    group: "{{ testlink_group }}"
    state: present

- name: Retrieve testlink group members.
  getent:
    database: group
    key: "{{ testlink_group }}"

- name: Ensure webserver user is in the testlink group.
  user:
    name: "{{ testlink_webserver_user }}"
    groups: "{{ testlink_group }}"
  when: not testlink_webserver_user in getent_group['{{ testlink_group }}'][2]

- name: Ensure testlink_app_dir is set.
  set_fact:
    testlink_app_dir: "{{ testlink_root_dir }}/testlink"

- name: Ensure testlink_install_dir is set.
  set_fact:
    testlink_install_dir: "{{ testlink_app_dir }}-{{ testlink_version }}"

- include_tasks: installation.yml
  when: testlink_version | lower != 'latest'

- include_tasks: latest.yml
  when: testlink_version | lower == 'latest'

- include_tasks: configuration.yml

- include_tasks: "{{ testlink_dbms }}.yml"
  when: testlink_dbms != False

- name: stat install directory.
  stat:
    path: "{{ testlink_app_dir }}/install"
  register: testlink_install

- name: Ensure install directory is absent.
  command: "mv {{ testlink_app_dir }}/install {{ testlink_app_dir }}/install.origin"
  args:
    creates: "{{ testlink_app_dir }}/install.origin"
  when: testlink_install.stat.exists
